openapi: "3.0.1"
info:
  title: "scratchpad-api"
  version: "0.1.0"
servers:
- url: "https://<REPLACE-WITH-ID>.execute-api.eu-central-1.amazonaws.com/<STAGE>"
paths:
  /Foo:
    post:
      summary: Create some foo stuff
      operationId: createFoo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Foo"
        required: true
  /ShortUrl:
    post:
      summary: Create some url stuff
      operationId: shortUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UrlShortener"
        required: true
components:
  schemas:
    UrlShortener:
      title: "UrlShortener"
      type: "object"
      properties:
        domainName:
          title: "UrlShortener.domainName"
          type: "string"
      additionalProperties: false
    Foo:
      title: "Foo"
      required:
      - "bar"
      type: "object"
      properties:
        bar:
          title: "Foo.bar"
          type: "string"
      additionalProperties: false
