=begin
#SkyBase API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ScratchpadApi::Foo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ScratchpadApi::Foo do
  let(:instance) { ScratchpadApi::Foo.new }

  describe 'test an instance of Foo' do
    it 'should create an instance of Foo' do
      expect(instance).to be_instance_of(ScratchpadApi::Foo)
    end
  end
  describe 'test attribute "bar"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
