=begin
#SkyBase API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'scratchpad-api/api_client'
require 'scratchpad-api/api_error'
require 'scratchpad-api/version'
require 'scratchpad-api/configuration'

# Models
require 'scratchpad-api/models/foo'
require 'scratchpad-api/models/url_shortener'

# APIs
require 'scratchpad-api/api/default_api'

module ScratchpadApi
  class << self
    # Customize default settings for the SDK using block.
    #   ScratchpadApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
